<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="BEAST" failures="1" tests="5" name="Personal Loan" time="0.044" errors="0" timestamp="2024-11-11T11:20:40 IST">
  <testcase classname="tests.Day2" name="ploan" time="0.008"/>
  <testcase classname="tests.Day1" name="secondTest" time="0.011">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at tests.Day1.secondTest(Day1.java:21)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- secondTest -->
  <testcase classname="tests.Day4" name="loginAPIHomeLoan" time="0.003"/>
  <testcase classname="tests.Day4" name="mobileLoginHomeLoan" time="0.001"/>
  <testcase classname="tests.Day4" name="webLoginHomeLoan" time="0.0"/>
  <testcase classname="tests.Day1" name="thirdTest" time="0.0">
    <ignored/>
  </testcase> <!-- thirdTest -->
  <testcase classname="tests.Day1" name="Demo" time="0.0">
    <ignored/>
  </testcase> <!-- Demo -->
</testsuite> <!-- Personal Loan -->
